name: Publish NuGet

on:
  push:
    branches: 
    - master
uses: rohith/publish-nuget@v2.1.1
  with:
    # Filepath of the project to be packaged, relative to root of repository
    PROJECT_FILE_PATH: Tetris.Core
