create table Customers(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(120) NOT NULL,
	Phone VARCHAR(120) NOT NULL,
	Email VARCHAR(120) NOT NULL,
	Creation DATETIME NOT NULL DEFAULT(GETDATE())
);
GO

CREATE TABLE Cars (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Description VARCHAR(120),
	PlatesNumber VARCHAR(45),
	Creation DATETIME NOT NULL DEFAULT(GETDATE())
);
GO

CREATE TABLE Customers_Cars (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CustomerId INT NOT NULL CONSTRAINT FK_Customers_Cars_CustomerId 
		FOREIGN KEY(CustomerId) REFERENCES Customers,
	CarId INT NOT NULL CONSTRAINT FK_Customers_Cars_CarId 
		FOREIGN KEY(CarId) REFERENCES Cars,
	Creation DATETIME NOT NULL DEFAULT(GETDATE())
);
GO

CREATE TABLE CustomersBanned(
	Id INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	CustomerId INT NOT NULL CONSTRAINT FK_CustomersBanned_CustomerId 
		FOREIGN KEY(CustomerId) REFERENCES Customers,
	Creation DATETIME NOT NULL DEFAULT(GETDATE())
);
GO

DROP TABLE CustomersBanned;

SELECT * FROM Customers;
SELECT * FROM Cars;
SELECT * FROM Customers_Cars;
SELECT * FROM CustomersBanned;